version: '3'
services:
  nginx:
   container_name: todo-nginx
   image: nginx:1.13
   restart: always
   ports:
   - 80:80
   - 443:443
   volumes:
   - ./nginx/conf.d:/etc/nginx/conf.d
   depends_on:
   - app
 
  mysql:
   container_name: todo-mysql
   image: mysql/mysql-server:5.7
   environment:
    MYSQL_DATABASE: tododb
    MYSQL_ROOT_PASSWORD: 143625
    MYSQL_ROOT_HOST: '%'

   ports:
   - "3306:3306"
   restart: always
  
  app:
    container_name: todo-app
    restart: always
    build: ./app
    ports:
      - "9090:8080"
    environment:
      MYSQL_DB_HOST: mysql:3306
    depends_on:
      # - nginx
      - mysql